### ISSUE TITLE
alternative to using resources

### ISSUE THREAD

**Issue by oscar-franzen** [omnivector-solutions/slurm-ops-manager#22]
If the resource is very large, say ~200Mb like the slurm snap, it will take extremely long time for juju to transfer the resource when the number of slurmd units is large.

One example is the following command:

`juju upgrade-charm slurmd --path ./slurmd.charm --resource slurm=slurm_20.02.1_amd64.resource`

**Comment by oscar-franzen** [comment]
A temporary workaround I used consists of transferring the resource using "juju scp" to a fixed path and then hard-coding the installation path inside slurm-ops-manager.

**Comment by jamesbeedy** [comment]
@oscar-franzen thank you for reporting this. We have a few bugs in with juju around this. There should be upstream fix in juju in the 2.9 release

**Comment by jamesbeedy** [comment]
@oscar-franzen we install from apt/yum now :)

Closing this.

Thanks!
