### ISSUE TITLE
using "juju config" interrupts running jobs

### ISSUE THREAD

**Issue by oscar-franzen** [omnivector-solutions/slurm-ops-manager#23]
Imagine a running slurm job. An administrator then runs `juju config slurmctld key=value` to change a configuration parameter for slurmctld, this will result in a restart of slurmctld and/or slurmd and running jobs will be terminated. The solution is for the charm to call `scontrol reconfigure` to force slurm to reload its config without restarting. I have tested this issue with `systemctl daemon-reload` and it does not reload slurm.conf.

**Comment by jamesbeedy** [comment]
Hey @oscar-franzen , Closing this issue because it has now been fixed with changes introduced in #29. Thank you!
